apiVersion: cloudscheduler.googleapis.com/v1
kind: Job
metadata:
  name: daily-car-dream-job
spec:
  schedule: "0 0 * * *"
  timeZone: "UTC"
  target:
    cloudRun:
      service: orchestrator
    httpMethod: POST
    uri: https://orchestrator.run.app/trigger