version: '3.8'

services:
  orchestrator:
    build: ./services/orchestrator
    ports:
      - "8080:8080"
    environment:
      - GCP_PROJECT_ID=${GCP_PROJECT_ID}
      - GCP_REGION=${GCP_REGION:-us-central1}
    depends_on:
      - reporter

  reporter:
    build: ./services/reporter
    ports:
      - "8081:8080"
    environment:
      - GCP_PROJECT_ID=${GCP_PROJECT_ID}
      - GCP_REGION=${GCP_REGION:-us-central1}

  # Note: CARLA and DreamerV3 services require GPU support
  # and are better deployed directly to GCP
  # Use deploy/deploy.sh for full cloud deployment